import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :front_end, FrontEnd.Repo,
  url: System.get_env("DATABASE_URL"), # DATABASE_URL is automatically set by Gigalixir
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "2"), # Default to 10 connections
  ssl: true, # Use SSL for connections
  queue_target: 2000, # Optional: Increases wait time before timeout
  queue_interval: 5000 # Optional: Reduces dropped requests due to long wait times

config :front_end, FrontEndWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: FrontEnd.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
